name: Scrape Talk Locations

on:
  push:
    paths:
      - 'talks/**'
      - '_talks/**'
      - 'talkmap.ipynb'
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: scrape-talks-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0            # ✅ 必须为 0，才能 rebase

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -U pip
          pip install jupyter pandas requests beautifulsoup4 geopy
          pip install -U getorg

      - name: Run Jupyter Notebook
        run: |
          jupyter nbconvert --to notebook --execute talkmap.ipynb --output talkmap_out.ipynb

      - name: Git config & auth
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          # ✅ 确保 remote 用带 token 的 URL
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Sync with remote (rebase to avoid non-FF)
        run: |
          git fetch origin ${{ github.ref_name }}
          # 如果落后就 rebase；冲突则放弃并用 pull --rebase 兜底
          if ! git diff --quiet HEAD origin/${{ github.ref_name }}; then
            git rebase origin/${{ github.ref_name }} || (git rebase --abort && git pull --rebase origin ${{ github.ref_name }})
          fi

      - name: Commit changes (if any)
        run: |
          git add -A
          git commit -m "Automated update of talk locations" || { echo "skip_push=true" >> $GITHUB_ENV; }

      - name: Push
        if: env.skip_push != 'true'
        run: |
          git push origin ${{ github.ref_name }}
          # 如果偶发竞态仍被拒，可改为下面一行（确认分支保护允许）：
          # git push --force-with-lease origin ${{ github.ref_name }}
